### ISSUE TITLE
Issues with scene export

### ISSUE THREAD

**Issue by timmyL17** [uhlik/render_maxwell#4]
Hi,

Thanks for this great module. I wanted to report an issue with scene export.
If the camera type is set to anything except thin lens, I get this error:

> writing cameras:
>         > 'Camera'
> Traceback (most recent call last):
>   File "/home/langlois/.config/blender/2.76/scripts/addons/blendmaxwell/ops.py", line 125, in execute
>     ex = export.MXSExport(mxs_path=p, )
>   File "/home/langlois/.config/blender/2.76/scripts/addons/blendmaxwell/export.py", line 97, in **init**
>     self._export()
>   File "/home/langlois/.config/blender/2.76/scripts/addons/blendmaxwell/export.py", line 978, in _export
>     self._write(o)
>   File "/home/langlois/.config/blender/2.76/scripts/addons/blendmaxwell/export.py", line 1383, in _write
>     if(mx.lens == 3):
> NameError: name 'mx' is not defined

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by uhlik** [comment]
ps. tested only on windows, my linux installation is messed up.. but windows and linux shares this part, so it should work

**Comment by timmyL17** [comment]
Yes, that seems to have fixed it. Thanks!
